### ISSUE TITLE
Ratelimiting

### ISSUE THREAD

**Issue by lokka30** [Lauriichan/Wildcard#1]
Hi there :smiley: thank you for this resource!
Does Wildcard rate-limit requests on the web interface? E.g. if a user and/or IP address makes more than 10 attempts, then lock them out temporarily.

**Comment by Lauriichan** [comment]
Currently not, but if you'd like such a feature I can look forward to implementing it.

**Comment by lokka30** [comment]
Only if you like. :smiley:

**Comment by Lauriichan** [comment]
So I think I added it.
It will ratelimit failed attempts.
Not based on the IP address tho atm.
As most users will probably not understand how the plugin works in the first place they won't be able to go around it.
As long as their session is valid (which is valid for 3 hours from the first opening of the web interface) they will be blocked from trying if they fail 5 times.
Fails are:
- Wrong Username
- Wrong Token
- Already Whitelisted
- Invalid Token

Do you think that is enough?
If not I could also look into IP Address ratelimiting but normally via session should be enough for normal users

**Comment by Lauriichan** [comment]
Added in e5faa14079534ae63dbf84569fcb0c8e5764dc28

**Comment by lokka30** [comment]
Thank you so much! I made sure to drop a review on the Spigot page. I think this plugin is in an excellent state now.
